export const data=[
    {
        id:1,
        english:"hello",
        french:"bonjour"
    },
    {
        id:2,
        english:"please",
        french:"sil vous plait"
    },
    {
        id:3,
        english:"sorry",
        french:"desolee"
    },
        {
        id:4,
        english:"sorry",
        french:"desolee"
    },
        {
        id:5,
        english:"sorry",
        french:"desolee"
    },
        {
        id:6,
        english:"where",
        french:"ou"
    },
        {
        id:7,
        english:"husband",
        french:"mari"
    },
        {
        id:8,
        english:"wife",
        french:"femme"
    },
    {
        id:9,
        english:"girl",
        french:"fille"
    },
        {
        id:10,
        english:"horse",
        french:"cheval"
    },
     {
        id:11,
        english:"horse",
        french:"cheval"
    },

]