export const data=[
    {
        id:1,
        english:"hello",
        french:"bonjour"
    },
    {
        id:2,
        english:"please",
        french:"sil vous plait"
    },
    {
        id:3,
        english:"sorry",
        french:"desolee"
    },
        {
        id:4,
        english:"sorry",
        french:"desolee"
    },
        {
        id:5,
        english:"sorry",
        french:"desolee"
    },
        {
        id:6,
        english:"where",
        french:"ou"
    },
        {
        id:7,
        english:"husband",
        french:"mari"
    },
        {
        id:8,
        english:"wife",
        french:"femme"
    },
    {
        id:9,
        english:"girl",
        french:"fille"
    },
        {
        id:10,
        english:"horse",
        french:"cheval"
    },
     {
        id:11,
        english:"USA",
        french:"Etas-unis"
    },
      {
        id:12,
        english:"pet",
        french:"animal de companie"
    },
    {
        id:13,
        english:"men",
        french:"homme"
    },

    {
        id:14,
        english:"boy",
        french:"garcon"
    },
    {
        id:15,
        french:"ami",
        english:"friend"
    },
    {
        id:16,
        french:"monde",
        english:"world"
    },
    {
        id:17,
        french:"travail",
        english:"work"
    },
    {
        id:18,
        french:"voyage",
        english:"trip"
    },
    {
        id:19,
        french:"ecole",
        english:"school"
    },
    {
        id:20,
        french:"livre",
        english:"book"
    },
    {
        id:21,
        french:"lumiere",
        english:"light"
    },

]